// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tokxmretmxhlggwbvzlf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRva3htcmV0bXhobGdnd2J2emxmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyODE2OTksImV4cCI6MjA2Mzg1NzY5OX0.JClmbwpX23qmlMS8acOaeZaTBPCml9taMvzDRScGpVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});