// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pephkpubvibxrqivfxjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlcGhrcHVidmlieHJxaXZmeGpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNjAxMDEsImV4cCI6MjA2OTczNjEwMX0.RdCQUiCLyjuzTkP1-F5055OVihuQ9zfcGT55xX3VMMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});