// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bytnzcacfsarviuqbpdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5dG56Y2FjZnNhcnZpdXFicGRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODA3NDMsImV4cCI6MjA3MDA1Njc0M30.44lit-IS4fAAsdRtg9xAFNPI1fdIbjsQUKI2bSiYC3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});